### ISSUE TITLE
Unable to run 'deno task serve'

### ISSUE THREAD

**Issue by gmlewis** [treehousedev/treehouse#305]
I'm on a Mac M2 Max running Sonoma 14.0, and got this:

```
glenn@glenn-MacM2Pro ~/src/github.com/treehousedev/treehouse (main) $ deno --version
deno 1.37.2 (release, aarch64-apple-darwin)
v8 11.8.172.13
typescript 5.2.2

glenn@glenn-MacM2Pro ~/src/github.com/treehousedev/treehouse (main) $ deno task serve
Task serve deno task lume -s
Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A - "-s"
Loading config file file:///Users/glenn/src/github.com/treehousedev/treehouse/_config.js

Warning Implicitly using latest version (v0.6.0) for https://deno.land/x/lume_markdown_plugins/toc.ts

TypeError: Module not found "https://deno.land/x/lume@v1.17.5/core/slugifier.ts".
    at https://deno.land/x/lume_markdown_plugins@v0.6.0/toc.ts:4:8
    at async createSite (https://deno.land/x/lume@v1.17.5/cli/run.ts:50:17)
    at async build (https://deno.land/x/lume@v1.17.5/cli/build.ts:33:16)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async (https://deno.land/x/lume@v1.17.5/cli.ts:134:3)
```

**Comment by catilac** [comment]
I'm getting the same issue. I checked out the [package source](https://deno.land/x/lume@v1.17.5/core/)
and `slugifier.ts` isn't there.

I looked into it a bit more, and `lume_markdown_plugins` is supposed to be `v.0.5.0` not 6. Not sure why it got the wrong dependency.

**Comment by progrium** [comment]
There's no escaping JavaScript package versions... is there a PR for this or is this upstream?

**Comment by catilac** [comment]
It's an upstream issue in lume. I managed to get past the error in an exploration by upgrading lume to latest, but that introduced layout issues that i haven't had much time to get into. could look into it later, but not sure i'm the best person to be doing it

**Comment by ajbouh** [comment]
@catilac I posted a short patch over in https://github.com/treehousedev/treehouse/issues/306 that pins the version of lume_markdown_plugins to an earlier one. It's one line and seems to work for me.

**Comment by ajbouh** [comment]
I just confirmed that this is now fixed in master. (The fix was in #309).
